### ISSUE TITLE
What is your touchpad model? Do you currently support multi-finger input?

### ISSUE THREAD

**Issue by xiaoMGitHub** [Malvik298/Hackintosh-LegionY530-High_Sierra#1]
Thank you for everything you have done for y530.

**Comment by Malvik298** [comment]
The touchpad is I2C (TPD0, Windows Precision Driver). As said the BIOS is interfering the touchpad connectivity in the OSX. And yes it supports multi-touch, includes 5 finger input.

**Comment by xiaoMGitHub** [comment]
@Malvik298 Why should I modify the BIOS? I didn't modify the BIOS, and the touchpad works fine.

**Comment by Malvik298** [comment]
I didnt got the touchpad working fine at starting, after tweaking few settings from BIOS I got my touchpad Working. And modifying BIOS is different thing and changing few settings from BIOS is different 😅😅. I just a workaroud to get my touchpad working .

**Comment by xiaoMGitHub** [comment]
This is my [hotpatch](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh_Clover/blob/master/ACPI/hotpatch/SSDT-I2C-GPI0.dsl), my touchpad is working very well right now.

**Comment by Malvik298** [comment]
Ohk. I'll try it. The patch i did just allowed me to use touchpad for few
seconds and after that it stopped working. I'll get you know if it works on
my end.
